[package]
name = "presage-store-sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0"

presage = { path = ".." }
# TODO: Take all types from presage instead of libsignal-service.
libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "791c521" }

async-trait = "0.1"
log = "0.4.8"
chrono = "0.4.24"
serde = "1.0"
serde_json = "1.0"

[patch.crates-io]
"curve25519-dalek" = { git = "https://github.com/signalapp/curve25519-dalek", branch = "lizard2" }
