[package]
# be a sign or warning of (an imminent event, typically an unwelcome one).
name = "presage"
version = "0.3.0"
authors = ["Gabriel Féron <feron.gabriel@gmail.com>"]
edition = "2021"

[dependencies]
# libsignal-service = { git = "https://github.com/whisperfish/libsignal-service-rs", rev = "1508fa8f3561e3807aa8d073ca05a61346ae5a82" }
# libsignal-service-hyper = { git = "https://github.com/whisperfish/libsignal-service-rs.git", rev = "1508fa8f3561e3807aa8d073ca05a61346ae5a82" }
libsignal-service = { path = "../libsignal-service-rs/libsignal-service" }
libsignal-service-hyper = { path = "../libsignal-service-rs/libsignal-service-hyper" }

async-trait = "0.1"
base64 = "0.12"
futures = "0.3"
hex = "0.4.2"
log = "0.4.8"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
sled = { version = "0.34", optional = true }
url = "2.2.2"
libsodium-sys = { version = "0.2.7", optional = true }
secrets = { version = "1.2.0", features = ["use-libsodium-sys"], optional = true }

[dev-dependencies]
# for tests
quickcheck = "1.0.3"
quickcheck_async = "0.1"

# for examples
anyhow = "1.0"
chrono = "0.4"
directories = "3.0"
env_logger = "0.7"
futures = "0.3"
hex = "0.4"
log = "0.4"
mime_guess = "2.0"
rand = "0.7"
serde_json = "1.0"
structopt = "0.3"
tempfile = "3.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "io-std", "io-util"] }
qr2term = { version = "0.2.2" }

[features]
default = ["sled-config-store","secret-volatile-config-store"]
quirks = []
sled-config-store = ["sled"]
secret-volatile-config-store = ["libsodium-sys","secrets"]
volatile-config-store = []

#[patch."https://github.com/whisperfish/libsignal-service-rs.git"]
#libsignal-service = { path = "../libsignal-service-rs/libsignal-service" }
#libsignal-service-hyper = { path = "../libsignal-service-rs/libsignal-service-hyper" }

[patch.crates-io]
"curve25519-dalek" = { git = 'https://github.com/signalapp/curve25519-dalek', branch = 'lizard2' }
